---
deployment:
  tasks:
    - export DEPLOYPATH=/home/leilapetcare/public_html/
    - /bin/cp *.html $DEPLOYPATH
    - /bin/cp send_mail.php $DEPLOYPATH
    - /bin/cp -r css $DEPLOYPATH
    - /bin/cp -r js $DEPLOYPATH
    - /bin/cp -r images $DEPLOYPATH
